### PR TITLE
Flow args

### PR DESCRIPTION
**Pull request by reillymck**
This pull request adds the following features:
- Error status triggers an exception. However, there is a parameter in the status constructor to prevent the exception from being raised. Checking for error status is now done in a try-catch block if you do not want the function to fail/return. 
- The framework for flow arguments is implemented. Xilinx flow arguments are supported for synthesis (SYNTH), including overwriting the default arguments for -dsp and -top. Xilinx implementation has been edited to work with designs synthesized out of context (constraints are not loaded and bitstream generation is skipped). CMP supports the argument "xilinx" or "lattice" (not case sensitive). This is directly fed into the VENDOR parameter when applicable.
    *Flow arguments include SYNTH, IMPL, MAP, EQUIV, CMP, & ERR
- Flow args are parsed into a dictionary with keys being the args and a string being the value. Currently for xilinx synthesis the entire SYNTH string is appended to the synth_design command. The flow args incorporate the new usage:
```
--synth FLOW_ARGS     Arguments for synthesis
--impl FLOW_ARGS      Arguments for implementation
--map FLOW_ARGS       Arguments for mapping
--equiv FLOW_ARGS     Arguments for equivalence
--cmp FLOW_ARGS       Arguments for comparison
--err FLOW_ARGS       Arguements for error flow
```
An example for xilinx flow would be:
```
run_design.py design_dir xilinx --synth "-mode out_of_context -flatten_hierarchy"
```
Or in the experiment .yaml file include:
```
synth: "-mode out_of_context -flatten_hierarchy"
```
- The flows.py file has been updated to include wrapper functions for each flow piece, ie: xilinx synthesis, yosys synthesis, yosys compare, etc. The flow functions now reference these wrappers. All flow functions accept a flow_args argument and all wrapper functions also accept the argument. The tool constructor also includes an optional flow_args parameter.
- Flow arguments can be specified in experiment .yaml files. They are not case-sensitive.
- run_experiment.py prints the output of each thread to build_dir/experiment_name/design/design_name.log
    *The running job and job completion status is still printed to stdout
    *References to print_to_stdout have been removed.
- run_experiment still only crashes when a Python Exception is raised and is not effected by the BfasstException (Status exceptions).

I have added a new .yaml "xilinx_ooc.yaml" which I used to test these new features. The command I used is
```
python scripts/run_experiment.py experiments/xilinx_ooc.yaml -j 8
```

### CODE REVIEW

**Comment by jgoeders** [comment]
@reillymck

**Comment by reillymck** [comment]
@jgoeders I guess none. Pablo added EQUIV, but I added CMP. I did not realize they overlapped.

**Comment by reillymck** [comment]
Right now the CMP Vendor arg is only fed into Conformal_CompareTool

**Review by dallinjdahl — APPROVED** [review]
Looks good

**Pull request merged**
